/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { QuizSession } from "./QuizSession";
import { QuizSessionCountArgs } from "./QuizSessionCountArgs";
import { QuizSessionFindManyArgs } from "./QuizSessionFindManyArgs";
import { QuizSessionFindUniqueArgs } from "./QuizSessionFindUniqueArgs";
import { DeleteQuizSessionArgs } from "./DeleteQuizSessionArgs";
import { QuizSessionService } from "../quizSession.service";
@graphql.Resolver(() => QuizSession)
export class QuizSessionResolverBase {
  constructor(protected readonly service: QuizSessionService) {}

  async _quizSessionsMeta(
    @graphql.Args() args: QuizSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [QuizSession])
  async quizSessions(
    @graphql.Args() args: QuizSessionFindManyArgs
  ): Promise<QuizSession[]> {
    return this.service.quizSessions(args);
  }

  @graphql.Query(() => QuizSession, { nullable: true })
  async quizSession(
    @graphql.Args() args: QuizSessionFindUniqueArgs
  ): Promise<QuizSession | null> {
    const result = await this.service.quizSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => QuizSession)
  async deleteQuizSession(
    @graphql.Args() args: DeleteQuizSessionArgs
  ): Promise<QuizSession | null> {
    try {
      return await this.service.deleteQuizSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
